apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-postgres-db
  name: auth-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/pulseone-backend-default: "true"
        io.kompose.service: auth-postgres-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:15-alpine
          name: auth-postgres-db
          ports:
            - containerPort: 5432
              hostPort: 5433
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-postgres-data
      restartPolicy: Always
      volumes:
        - name: auth-postgres-data
          persistentVolumeClaim:
            claimName: auth-postgres-data
status: {}
