apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: profile-postgres-db
  name: profile-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile-postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: profile-postgres-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: profiledb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:15-alpine
          name: profile-postgres-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: profile-postgres-data
      restartPolicy: Always
      volumes:
        - name: profile-postgres-data
          persistentVolumeClaim:
            claimName: profile-postgres-data